language: java
jdk:
- openjdk8
install: true
script: mvn clean package
before_deploy:
- pwd
- ls
deploy:
  provider: releases
  api_key:
    secure: S6YYbbDCqeCIAl7N2XL+Rd2ck1QhqMCivWwkchZGZYlHkLnTMyFa9u0dnm+sk8NV2+ugl5rR7m+mMlS/iAG/x3LRFHtmojivLII0PIS+WC9DpbMtYe7+z8IW6nfiNXxGlUuKrw7xd9iDzz8wvv6ig/xEaPIGrOPwy7+K0Edt7CoGYWy1qo2XhCtJxILecAo5aPMnjUhIEpbLawljuTNPD11r90PQ7dxjg0Rw2mxteDPk+XfpG5mZmQGVZfV31lO67A0p/KAf+kpBka9lSXPOPN+GS7FFPYcBqYojDYE7TvTggQVfOGw7Bfwyb6/f/iI7svC+izCok3lvJs9zxZLLfAoFO5vVYFYtc+4Dd5clpV1fqeP+HVBRVPSJLKIKxOMLyYKDfRxR0oJmwRkLb7lbxOr3iqRb/fO7M69bL1HWXeo9IGRaVcL3TSDWN14dTqQ6srTiBpVVtQrRyu8hJVn89YUl+vvZbp+YekL0I3mZrrhbUU5ftxEymWw3gn/VbKur3Jw1kmMG6lrW71gOscJMNSaVQpDjnL6bFTQEh1hNIcL0T37Iw1aKcp9p0GghTAj32a/ADaAMR3sDJ8ZmtsPwm56S6JoGaMyYavP0yV29tCn4zu9voti/uPs0scZ+86d6+TySnfV8hFEeCfWCsjoGDeQRNoL/hFpXLMvV+lgzUv0=
  file: target/cloudmonitor-0.0.1-SNAPSHOT.jar
  on:
    repo: abryu/cloudmonitor
    tags: true
    all_branches: true
