language: java
jdk:
- openjdk8
install: true
script: mvn clean package
before_deploy:
- pwd
- ls
deploy:
  provider: releases
  api_key:
    secure: Ab/e4xFnELQG6/3C/s8b1MtRj+SMJcGnROZZqCsHhcfItGmLclYJ4GQn3HtLKd7PeGAer22SkVjriWQgZ9lFS5ycWaG1M2nAb4Hiyar7Vdhc4b48B007/adLS0BV3gbITdMshZpdjemwjasMt5UJbmhvZsZEEo6YoLQxcyed/VVUdYaY99ZxJkeaos4NqVQ5DANg3gSBQ7denRcBCLiJFJtYjAMxrWB8Ha1GOZ+HooUb+NiiRF6U5yF5TuG+oq1uFcvV/m7iu7gTGzyt6G1UxOcG+8s6l4qnGXtmZnvwAAj1LgNIkgBnv5ZuQedqSNc3VNM0GM0Fv8hDbCx0niMHuDh448UmZ+9+4aYkByeyr3QvZQFymmXlNzY368MN/nXQJd+LQLy7P+4qW4Hh7pHzoA2kCRRh24gOKjd5k9OBuBI27DBd05PGuE6D1RFkdDatDfRHLtbeD2QGEUZfsoNGarW0aBpTJS9lSPvl5ZWrtbkYx3HiHldWJLiARhwZ0WcreUoJ4LcFkFtsVyy5d301S6zMKQ6bviGAn6HsqKaMgOQap36viMmKLh1P71J96o0Vqe+h1pHnrJscZU3bbPP2/cEyg7jJR83KUI3vN5tjQVdAqCSwvXEj110dquXIoqkDRaa6AJlcQeIL0YdiQJoNgRwcOeSOabhOxniEfW54zQI=
  file: target/cloudmonitor-0.0.1.SNAPSHOT.jar
  on:
    repo: abryu/cloudmonitor
